const BASE_URL = 'https://theremin.music.uiowa.edu/sound files/MIS/Piano_Other/piano/';

export const soundMap: { [note: string]: string } = {
    'C4': `${BASE_URL}Piano.mf.C4.aiff`,
    'Db4': `${BASE_URL}Piano.mf.Db4.aiff`,
    'D4': `${BASE_URL}Piano.mf.D4.aiff`,
    'Eb4': `${BASE_URL}Piano.mf.Eb4.aiff`,
    'E4': `${BASE_URL}Piano.mf.E4.aiff`,
    'F4': `${BASE_URL}Piano.mf.F4.aiff`,
    'Gb4': `${BASE_URL}Piano.mf.Gb4.aiff`,
    'G4': `${BASE_URL}Piano.mf.G4.aiff`,
    'Ab4': `${BASE_URL}Piano.mf.Ab4.aiff`,
    'A4': `${BASE_URL}Piano.mf.A4.aiff`,
    'Bb4': `${BASE_URL}Piano.mf.Bb4.aiff`,
    'B4': `${BASE_URL}Piano.mf.B4.aiff`,
    'C5': `${BASE_URL}Piano.mf.C5.aiff`,
    'Db5': `${BASE_URL}Piano.mf.Db5.aiff`,
    'D5': `${BASE_URL}Piano.mf.D5.aiff`,
    'Eb5': `${BASE_URL}Piano.mf.Eb5.aiff`,
    'E5': `${BASE_URL}Piano.mf.E5.aiff`,
    'F5': `${BASE_URL}Piano.mf.F5.aiff`,
    'Gb5': `${BASE_URL}Piano.mf.Gb5.aiff`,
    'G5': `${BASE_URL}Piano.mf.G5.aiff`,
    'Ab5': `${BASE_URL}Piano.mf.Ab5.aiff`,
    'A5': `${BASE_URL}Piano.mf.A5.aiff`,
    'Bb5': `${BASE_URL}Piano.mf.Bb5.aiff`,
    'B5': `${BASE_URL}Piano.mf.B5.aiff`,
};
